# Generated by Django 5.0.6 on 2024-06-07 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("dept1", "Cardiology"),
                            ("dept2", "Neurology"),
                            ("dept3", "Hepatology"),
                            ("dept4", "General Physician"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "doctor",
                    models.CharField(
                        choices=[
                            ("doctor1", "Jhon Jackson"),
                            ("doctor2", "Amy Jacob"),
                            ("doctor3", "Jing Who"),
                            ("doctor4", "Jane Anderson"),
                            ("doctor5", "Ricky Nathan"),
                            ("doctor6", "Nelson John"),
                            ("doctor7", "Patrick Shiong"),
                            ("doctor8", "Solange Falade"),
                        ],
                        default="doctor8",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Available"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=50)),
                ("uemail", models.CharField(max_length=50)),
                ("ucmts", models.CharField(max_length=200)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("bad", "bad "),
                            ("good", "good"),
                            ("excellent", "excellent"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="product name")),
                ("price", models.FloatField()),
                (
                    "pdetails",
                    models.CharField(max_length=500, verbose_name="Product Details"),
                ),
                (
                    "cat",
                    models.IntegerField(
                        choices=[
                            (1, "Medicine"),
                            (2, "Personalcare"),
                            (3, "Unicare"),
                            (4, "Covid19"),
                        ],
                        verbose_name="Category",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Available"),
                ),
                ("pimage", models.ImageField(upload_to="image")),
            ],
        ),
        migrations.CreateModel(
            name="Appoint_History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("date", models.DateField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("dept1", "Cardiology"),
                            ("dept2", "Neurology"),
                            ("dept3", "Hepatology"),
                            ("dept4", "General Physician"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "doctor",
                    models.CharField(
                        choices=[
                            ("doctor1", "Jhon Jackson"),
                            ("doctor2", "Amy Jacob"),
                            ("doctor3", "Jing Who"),
                            ("doctor4", "Jane Anderson"),
                            ("doctor5", "Ricky Nathan"),
                            ("doctor6", "Nelson John"),
                            ("doctor7", "Patrick Shiong"),
                            ("doctor8", "Solange Falade"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(default=" ")),
                (
                    "aid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("date", models.DateField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("dept1", "Cardiology"),
                            ("dept2", "Neurology"),
                            ("dept3", "Hepatology"),
                            ("dept4", "General Physician"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "doctor",
                    models.CharField(
                        choices=[
                            ("doctor1", "Jhon Jackson"),
                            ("doctor2", "Amy Jacob"),
                            ("doctor3", "Jing Who"),
                            ("doctor4", "Jane Anderson"),
                            ("doctor5", "Ricky Nathan"),
                            ("doctor6", "Nelson John"),
                            ("doctor7", "Patrick Shiong"),
                            ("doctor8", "Solange Falade"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(default=" ")),
                (
                    "aid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="customer_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("firstname", models.CharField(max_length=50, null=True)),
                ("lastname", models.CharField(max_length=50, null=True)),
                ("mobile", models.BigIntegerField(null=True)),
                ("address", models.CharField(max_length=350, null=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=30)),
                ("qty", models.IntegerField(default=1)),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        db_column="pid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthapp.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField(default=1)),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        db_column="pid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthapp.product",
                    ),
                ),
            ],
        ),
    ]
